add test cases for internal/metrics/prometheus.go
defenseunicorns/uds-security-hub pull request #291
Opened 2024-09-25 18:38 UTC by benjaminwilcox

add test cases for internal/metrics/prometheus.go

2024-09-26 21:20 UTC, partkyle commented on internal/metrics/prometheus_test.go
> +		t.Fatal("expected no error when unregistering non-existent counter")
should log the err too so we know what it is. Usually a `Fataf` with a `%v` is good at the end.

2024-09-26 21:55 UTC, partkyle requested changes
There's a solid argument for deleting this whole package. We don't do anything with these prometheus metrics as far as I'm aware. We don't store them or publish them anywhere.

Can you verify that this is not used externally, and if so we should just delete it instead. That will push up coverage too.

2024-09-27 17:29 UTC, benjaminwilcox commented
> There's a solid argument for deleting this whole package. We don't do anything with these prometheus metrics as far as I'm aware. We don't store them or publish them anywhere.
> 
> Can you verify that this is not used externally, and if so we should just delete it instead. That will push up coverage too.

I don't see it being used externally, but I saw this issue that Naveen has open: https://github.com/defenseunicorns/uds-security-hub/issues/73 looks like there were plans for it?

2024-09-30 18:15 UTC, partkyle approved these changes

2024-09-30 18:24 UTC, merged